# SRC = find src/ -name "\*.c" -exec echo "\{\} \" \;
SRC = \
src/parse_rt/parse_rule_shapes.c \
src/parse_rt/rt_file.c \
src/parse_rt/clamp.c \
src/parse_rt/rt_file_set.c \
src/parse_rt/parse_rule_square.c \
src/parse_rt/count_rules.c \
src/parse_rt/parse_rule_non_shape.c \
src/main.c \
src/exit.c \
src/constants.c \
src/gui/gui.c \
src/gui/save_bmp.c \
src/gui/gui2.c \
src/gui/gui_init.c \
src/ray/is_clear_path.c \
src/ray/compute_color.c \
src/ray/vector.c \
src/ray/normalize.c \
src/ray/render/render_bonus.c \
src/ray/render/render.c \
src/ray/vector2.c \
src/ray/ray_to_color.c \
src/ray/intersect/intersect_sphere.c \
src/ray/intersect/intersect_cylinder.c \
src/ray/intersect/intersect.c \
src/ray/intersect/intersect_triangle.c \
src/ray/intersect/intersect_plane.c \
src/ray/ray_from_pix.c \
src/ray/color.c \
src/ray/quadratic.c \
