# SRC = find src/ -name "\*.c" -exec echo "\{\} \" \;
SRC = \
src/ft_putnbr_fd.c \
src/ft_lstadd_front.c \
src/ft_putendl_fd.c \
src/ft_strtodbl.c \
src/ft_strncpy.c \
src/ft_memcmp.c \
src/ft_readbuf.c \
src/ft_memccpy.c \
src/ft_lstnew.c \
src/ft_strset.c \
src/ft_strndup_unsafe.c \
src/ft_realloc.c \
src/ft_strtonum_u.c \
src/ft_lstclear.c \
src/ft_lstshift.c \
src/ft_lstpush_back.c \
src/ft_get_next_line.c \
src/ft_strncat.c \
src/ft_degrees.c \
src/ft_arr.c \
src/ft_strnstr.c \
src/ft_get_next_line2.c \
src/ft_isprint.c \
src/ft_strcat.c \
src/ft_memset.c \
src/ft_numtobase.c \
src/ft_lstsize.c \
src/ft_lstpush_front.c \
src/ft_memdup.c \
src/ft_strjoin.c \
src/ft_strcpy.c \
src/ft_strtoupper.c \
src/ft_strchr.c \
src/ft_atoi.c \
src/ft_memcpy.c \
src/ft_split_or.c \
src/ft_arrchr.c \
src/ft_putchar_fd.c \
src/ft_memchr.c \
src/ft_split.c \
src/ft_abs.c \
src/ft_memmove.c \
src/ft_strlcpy.c \
src/ft_substr.c \
src/ft_lstdelone.c \
src/ft_isalpha.c \
src/ft_calloc.c \
src/ft_numtobase_u.c \
src/ft_lstadd_back.c \
src/ft_max.c \
src/ft_strrchr.c \
src/ft_lstmap.c \
src/ft_free_until_null.c \
src/ft_toupper.c \
src/ft_strncmp.c \
src/ft_split_file.c \
src/ft_free_2d.c \
src/is_power_of_2.c \
src/ft_isalnum.c \
src/ft_strlen.c \
src/ft_isspace.c \
src/ft_bzero.c \
src/ft_isdigit.c \
src/ft_strtonum.c \
src/ft_strcount.c \
src/ft_isascii.c \
src/ft_strtrim.c \
src/ft_strcmp.c \
src/ft_strlcat.c \
src/ft_numtostr.c \
src/ft_tolower.c \
src/ft_split_length.c \
src/ft_putstr_fd.c \
src/ft_lstlast.c \
src/ft_radians.c \
src/ft_numtostr_u.c \
src/ft_lstiter.c \
src/ft_readfile.c \
src/ft_putstr.c \
src/ft_itoa.c \
src/ft_malloc.c \
src/ft_arr2.c \
src/ft_numlen.c \
src/ft_includes.c \
src/ft_strtolower.c \
src/ft_numlen_u.c \
src/ft_min.c \
src/ft_strmapi.c \
src/ft_strndup.c \
src/ft_strdup.c \
